
# A string that specifies the project ID
project_id = "tqvylbkavunzlckhqxcl"

[functions]
  [functions.company-analysis]
  verify_jwt = false
  
  [functions.french-company-registry]
  verify_jwt = false
