
# A string used as a secret for the Edge Functions JWT.
project_id = "tqvylbkavunzlckhqxcl"

[functions]
[functions.app_dir]
app_dir = "dist"

[functions.env]
# Keys are accessible from Edge Functions as they run
SUPABASE_URL = "***"
SUPABASE_ANON_KEY = "***"
SUPABASE_SERVICE_ROLE_KEY = "***"
OPENAI_API_KEY = "***"
