
# A string used as a secret for the Edge Functions JWT.
project_id = "tqvylbkavunzlckhqxcl"

[build]
  [build.functions]
    node_version = 18
    app_dir = "dist"

  [build.functions.deploy]
    include = []
    exclude = []

[env]
OPENAI_API_KEY = "***"
SUPABASE_URL = "***"
SUPABASE_ANON_KEY = "***"
SUPABASE_SERVICE_ROLE_KEY = "***"
