
# A string that specifies the project ID
project_id = "tqvylbkavunzlckhqxcl"

# Configuration for Functions
[functions]
[functions.serve]
app_dir = "dist"
node_version = "18"

[functions.deploy]
include = []
exclude = []

# Environment variables
[global.env]
OPENAI_API_KEY = "***"
SUPABASE_URL = "***"
SUPABASE_ANON_KEY = "***"
SUPABASE_SERVICE_ROLE_KEY = "***"
