
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.23.0";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface RequestData {
  industry: string;
  industry_name: string;
  followsStandards: boolean;
  selectedStandards: string[];
  reportContent: string;
  email?: string;
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    console.log("Generating ESG QuickStart report");
    
    // Create a Supabase client with the service role key
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
      {
        auth: {
          autoRefreshToken: false,
          persistSession: false,
        },
      }
    );

    // Parse the request body
    const requestData: RequestData = await req.json();
    
    try {
      // Process the report content
      const reportText = requestData.reportContent;
      
      // Format the content for online viewing with simple HTML formatting
      const onlineContent = reportText.replace(/\n\n/g, '</p><p>')
                                     .replace(/\n/g, '<br>')
                                     .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
                                     .replace(/\*(.*?)\*/g, '<em>$1</em>');
      
      const htmlReport = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>ESG QuickStart Report - ${requestData.industry_name}</title>
          <meta charset="utf-8">
          <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
            h1, h2, h3 { color: #1e40af; }
            .header { border-bottom: 1px solid #e5e7eb; padding-bottom: 15px; margin-bottom: 20px; }
            .content { margin-bottom: 30px; }
            .footer { border-top: 1px solid #e5e7eb; padding-top: 15px; font-size: 0.9em; color: #6b7280; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>ESG QuickStart Report</h1>
            <p>Industry: ${requestData.industry_name}</p>
          </div>
          <div class="content">
            <p>${onlineContent}</p>
          </div>
          <div class="footer">
            <p>Generated by ELIA GO ESG Platform</p>
          </div>
        </body>
        </html>
      `;
      
      // If email is provided, send the report by email
      if (requestData.email) {
        try {
          // This would be implemented in a real application
          // We'd connect to an email service like SendGrid or use SMTP
          console.log(`Sending report to email: ${requestData.email}`);
          
          // In a real implementation, this would be a call to an email service
        } catch (emailError) {
          console.error("Error sending email:", emailError);
        }
      }
      
      // Encode the content as base64 (simulating a PDF)
      const encoder = new TextEncoder();
      const reportBytes = encoder.encode(reportText);
      const reportBase64 = btoa(String.fromCharCode(...new Uint8Array(reportBytes)));
      
      // Create a base64 representation of the HTML version for online viewing
      const htmlBytes = encoder.encode(htmlReport);
      const htmlBase64 = btoa(String.fromCharCode(...new Uint8Array(htmlBytes)));
      
      return new Response(
        JSON.stringify({
          success: true,
          data: {
            reportBase64,
            htmlBase64,
            fileName: `ESG_QuickStart_${requestData.industry}_Report.pdf`,
            mimeType: 'application/pdf',
            onlineVersion: true
          },
        }),
        {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 200
        }
      );
    } catch (pdfError) {
      console.error("Error generating PDF:", pdfError);
      throw new Error(`PDF generation failed: ${pdfError.message}`);
    }
  } catch (error) {
    console.error("Error in generate-esg-report function:", error);
    
    return new Response(
      JSON.stringify({ 
        success: false, 
        error: error.message || "Failed to generate report" 
      }),
      { 
        status: 500, 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    );
  }
});
